### ISSUE TITLE
Support Document Metadata within Comments

### ISSUE THREAD

**Issue by zhanbei** [zhanbei/Markdown-Site-Generator#1]
```yaml
meta: true
metadata: true
date: 2019-10-29T13:44:21+0800
key: Support-Document-Metadata.md
```
